<?php

namespace Blog\BadgeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * userBadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userBadgeRepository extends EntityRepository
{
}
