<?php

namespace Api\ResetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthCodeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class AuthCodeRepository extends EntityRepository
{
}
