<?php

namespace Api\RestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RefreshTokenRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RefreshTokenRepository extends EntityRepository
{
}
